### PR TITLE
Added few from my library

### PR DESCRIPTION
**Pull request by TheFenrisLycaon**
Added a few games like ::

- Brickout Game
- Flappy Bird
- Tetris
- Tic Tac Toe
- Dice Rolling Simulator
- Snake 
 
A few algorithm demos like:

- A Star Path Finder :: Implementation of this algo

A few apps like :

- Basic clock :: Clock GUI app
- Koch Curve :: Draws a koch curve using turtle 
- AR Invisibility Cloak :: Uses opencv to create a cloak of invisibility

### CODE REVIEW

**Comment by TheFenrisLycaon** [comment]
Hey, add me to the contributors list if you do decide to merge this (which you should). Thanks !

**Comment by TheFenrisLycaon** [comment]
@Graey ...

**Comment by Graey** [comment]
Deleted the progs which were already in the repo base. Dekh liya karo main branch ko upload karne se pehle!

**Comment by TheFenrisLycaon** [comment]
Can you add the hacktoberfest accepted label to this one.

**Comment by Graey** [comment]
Sure bhai, kuch to mile tumhe bhi !

**Comment by TheFenrisLycaon** [comment]
Also lmk if I can contribute more yk !

**Pull request merged**
