### PR TITLE
Calculating A Factorial Of A Number Through Recursion

### PR DESCRIPTION
**Pull request by AryashDubey**

### CODE REVIEW

**Comment by Graey** [comment]
jaagte raho, kaam karte raho! I hope this was a nice surprise for you :)

**Comment by AryashDubey** [comment]
Yeah Thank You Very Much!!!!!!!!

**Comment by AryashDubey** [comment]
Maine Ek Game bhi banaya hai Python pe

**Comment by AryashDubey** [comment]
Should I upload It!?

**Comment by Graey** [comment]
Yes !

**Pull request merged**
